### ISSUE TITLE
You beat me to it

### ISSUE THREAD

**Issue by Frankkkkk** [eelkjaer/BarryAPIClient#1]
Well, github's search is crappy..
I just discovered your repo searching for `co.getbarry` :P

Here's mine in any case you want to merge efforts: https://github.com/Frankkkkk/python-barry-energy

Still missing some things, as I can't test MPAN consumption for now :'(

Cheers

**Comment by eelkjaer** [comment]
API Key is missing.

create a file called “credentials.py” and make a def called `getApiKey()` which returns the API Key from Barry as a String. :-)

Will push a fix later

**Comment by eelkjaer** [comment]
Closed with last commit

**Comment by Frankkkkk** [comment]
Nice copy/paste 😂 ;-)

**Comment by eelkjaer** [comment]
Is there any way to get in touch with you?

**Comment by Frankkkkk** [comment]
Of course !
You can either see my e-mail on my profile : https://github.com/Frankkkkk or in each of my commits .
Cheers
